-- Seed initial flash-card deck products
INSERT INTO products (
    id,
    name,
    description,
    price,
    stock_quantity,
    slug,
    title,
    badge,
    badge_class,
    rating,
    reviews,
    original_price,
    discount,
    main_image,
    gallery_images,
    cards_count,
    created_at,
    updated_at
) VALUES
(
    'a4d312a9-b63e-4327-8b3f-dd42bfe738bf',
    'Chhatrapati Shivaji Maharaj: The Great Maratha',
    'Master the legend of the Maratha Empire. This collector''s edition includes 52 beautifully illustrated cards covering the Coronation, Guerrilla Warfare tactics, Administration (Ashta Pradhan), and the architectural marvels of Sea Forts.',
    899,
    100,
    'shivaji-maratha',
    'Chhatrapati Shivaji Maharaj: The Great Maratha',
    'TOP RATED',
    'badge-top-rated',
    4.9,
    2104,
    1299,
    '30% OFF',
    '/images/maharaj_800_600.png',
    ARRAY['/images/2nd_maharaj.png', '/images/3rd_maharaj.png'],
    52,
    NOW(),
    NOW()
),
(
    '358c2b76-8025-4b0d-9b1d-91b5c490ec31',
    'Ramayana: The Epic Visual Deck',
    'Visual storytelling through flashcards covering all 7 Kandas of the Ramayana.',
    1299,
    100,
    'ramayana-epic',
    'Ramayana: The Epic Visual Deck',
    'NEW ARRIVAL',
    'badge-new',
    4.8,
    850,
    NULL,
    NULL,
    '/images/best_ramayana.png',
    ARRAY[]::TEXT[],
    108,
    NOW(),
    NOW()
),
(
    '7b11d87f-9486-4f4f-80d5-5eb7127e2d93',
    'UPSC Polity Master Set',
    'Complete coverage of Laxmikanth, Constitutional Articles, and Amendments.',
    1999,
    100,
    'upsc-polity',
    'UPSC Polity Master Set',
    'BEST SELLER',
    'badge-bestseller',
    4.7,
    5420,
    NULL,
    NULL,
    '/images/best_polity.png',
    ARRAY[]::TEXT[],
    250,
    NOW(),
    NOW()
);
